[package]
name = "chapter18-1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
serde = "1.0.219"
serde_json = "1.0.140"
reqwest = { version = "0.11", features = ["blocking"] }
