[package]
name = "photo-share-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
axum = "0.8.1"
async-graphql = "7.0.15"
async-graphql-axum = "7.0.15"
chrono = "0.4.40"
