[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.6.14"
cortex-m-semihosting = "0.3.7"
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
stm32f4xx-hal = {version="0.7.0", features=["stm32f407"]}
