[package]
name = "chapter5-1"
version = "0.1.0"
edition = "2024"

[features]
derive = ["syn"]
default = ["derive"]

[dependencies.syn]
version = "1"
default-features = false
features = ["derive", "parsing", "printing"]
optional = true
